### ISSUE TITLE
Provide a script to uninstall alidock

### ISSUE THREAD

**Issue by mconcas** [alidock/alidock#101]
Ok, this is something we would not like to see, but...

 - It should be as easy as installing it.
 - we should provide some pointer in the documentation to some kind of uninstall procedure for docker as well.

**Comment by dberzano** [comment]
Basically to uninstall alidock you need to do `pip uninstall` if installed manually - or, you need to remove completely your `alidock` virtualenv. We can go further and remove any reference to `alidock` to any shell script if you want.

First step is, in any case:

```
rm -rf ~/.virtualenvs/alidock
```

and that's it. I would document it rather than scripting it 😄 How would you do it?
