### ISSUE TITLE
load ALIROOT/ALIPHYSICS environment outside alidocker

### ISSUE THREAD

**Issue by pachmay** [alidock/alidock#103]
Hi Dario,

it possible to like in the past simply load the environment, without entering alidocker and to execute my macros? Or do I have to delete my alidocker installation and go back to aliBuild?

Ciao
Yvonne

**Comment by dberzano** [comment]
Hello @pachmay, I am not sure I understand the issue here. You either use `alidock`, or you don't. Think of it: you are asking, on the alidock support channel, how to **not** use it.

alidock is the recommended way because the runtime environment is known and support is easier for you.

Closing; feel free to open a new issue if you have problems/questions _concerning using alidock_ 😄
