### ISSUE TITLE
Cannot open alidock

### ISSUE THREAD

**Issue by efgauger** [alidock/alidock#156]
Hello,

Yesterday, my alidock would not open and gave the following error: 
"Updating alidock automatically
+ python3 pypa-virtualenv-d5fed23/virtualenv.py /Users/efgauger/.virtualenvs/alidock
/dev/fd/63: line 25: /Users/efgauger/.virtualenvs/alidock/bin/python3: No such file or directory"

I had no problems with my alidock before this. I tried reinstalling alidock, after seeing a relevant email thread to the analysis task force list, but it did not work. Now, I get the message "Starting a shell into the container" but the alidock environment never opens. 

Versions:
macOS Mojave version 10.14.6
docker version 2.1.0.4 (39773)
python 2.7.16 and python3 3.7.5

![Screen Shot 2020-08-31 at 11 08 44 AM](https://user-images.githubusercontent.com/26318112/91872818-ef4a3700-ec3d-11ea-88ef-93fb2ffc715f.png)

**Comment by mconcas** [comment]
Can you try to give
`docker pull alisw/alidock` 
And see if the container has been downloaded?

Also are you sure the old container is not running? Can you try with
`alidock stop` and then `alidock` again?

**Comment by efgauger** [comment]
Thanks for the quick response! 
I tried "docker pull alisw/alidock" and got the following output: 
![Screen Shot 2020-09-02 at 10 40 52 AM](https://user-images.githubusercontent.com/26318112/92005564-3fda9680-ed09-11ea-8154-441448289bfe.png)

I then tried to stop and restart alidock:
![Screen Shot 2020-09-02 at 10 41 29 AM](https://user-images.githubusercontent.com/26318112/92005711-6a2c5400-ed09-11ea-93b8-efcca6820a67.png)

This looked a bit promising, so I opened a new terminal window to see if alidock would now work smoothly. I now get the following error: 
![Screen Shot 2020-09-02 at 10 46 49 AM](https://user-images.githubusercontent.com/26318112/92006017-d1e29f00-ed09-11ea-9989-0713b878f9bb.png)

**Comment by mconcas** [comment]
To me it looks that you succeed in entering the container, to test it, can you do `cat /etc/os-release` ?
As a matter of fact, you cannot use the alidock command since it is not installed there.
Also the prompt inside the container seems to be messed up, with respect to what you should have as a default, hence the errors at the login. Did you change the `.bashrc` of your shell in the docker container?

As last remark: once you enter alidock, typing the `alidock` command, you still have to use `alienv enter` and other `aliBuild` commands. It does not behave as a substitution for them. That's why the `root ` and `aliroot` command don't work.

**Comment by efgauger** [comment]
Hi,
Everything seems to be working now. Sorry I forgot to do the alienv enter command in the screenshot. 
I'm not sure why I got the errors when I entered the environment, but they are no longer there. (I haven't touched the .bashrc in alidock.)
Thanks a lot for your help.
