### ISSUE TITLE
problem with alidock on a shared system

### ISSUE THREAD

**Issue by pchrista** [alidock/alidock#182]
Hi all,
I'm trying to get alidock up and running on a shared fs on CentOS7 machines
I created an alias for alidock:

alias alidock='alidock --shared /data/alice/pchrist/alidock'

but when running the command I get:

bash|nass> alidock
Creating container, hold on
Starting a shell into the container
Cannot continue: cannot log into the container, maybe it did not start up properly: check log file /data/alice/pchrist/alidock/.alidock-alidock/log.txt for details and make sure your Docker version is updated. Error: '22/tcp'

The log file is empty
Any suggestions will be highly appreciated!

**Comment by pchrista** [comment]
I forgot to say that I don't think it's a rights issue

**Comment by mconcas** [comment]
Sorry for overlooking this. Unfortunately I don't currently support shared filesystems with alidock. The reason is heavily entangled to the many types of shared filesystem available and their possible integration is really managed at docker level.
So, while I expect that in many cases it can just work seamlesslly, I am not in force to cover all possible scenarios.
As a side note, since you are running already on a Centos 7 machine I suggest to use aliBuild natively, you will have all the benefits that alidock takes from CentOS containers.
