### ISSUE TITLE
Make Dropbox/cernbox visible in the container automatically

### ISSUE THREAD

**Issue by dberzano** [alidock/alidock#52]
We might have a perfectly legitimate use case of users wanting to expose some directories other than alidock inside the container.

For instance, it would be maybe nice to have `~/Dropbox` and `~/cernbox` automatically exposed, somehow. (Maybe, I said.)

cc @tomas-herman

**Comment by mconcas** [comment]
Since it will be strictly related to this work, I suggest to add the `/cvmfs` availability/support option to this topic. As we well know, it would require the `shared` bind-propagation flag, and this must be imposed, in order to make it work.
AFAIK, correct me if I'm wrong, no other technology we are supporting in the near future needs for some (more) specific flags.

So, here is my question, do _we_ want to treat the cvmfs as a separate flag? (`--cvmfs [custom/path]`) Just to be sure that the correct options are passed to the bind chain.

I would also propose to mount, if not differently specified, all bind path in read-only mode, in order to stimulate people to write in the `alidock` directory. This is also the safest assumption.

Just brainstorming, anyway.

**Comment by dberzano** [comment]
See #64.
