### ISSUE TITLE
Stop container automatically if no sessions active for a while

### ISSUE THREAD

**Issue by dberzano** [alidock/alidock#56]
Allows the next runs of `alidock` to also update the container.

**Comment by olantwin** [comment]
How would you define active session? I can imagine opening a `tmux` in the container for some long-running process and then disconnecting for several hours before checking on it again. Returning to find that the container has shut down could be very surprising.

**Comment by dberzano** [comment]
Of course we need to detect tmux/screen/etc. sessions. Do you have any ideas on how to do that yourself? Consider this ticket as a RFC, not a letter of intentions 😄 

The problem I am trying to solve is that I'd like container images to update automatically as soon as possible, and this is obviously not possible if the user has active sessions.

We have seen yesterday that users get confused even when they see a message saying "update alidock NOW": they don't know whether to trust the message, and they don't know how to adapt the update command to their custom installation or virtual environment. Printing a similar message saying "stop alidock to update the image" would lead, I believe, to similar support questions and other support problems.

I'd really like this thing to work as automatically as possible.

In case we can safely detect running sessions, and there are none, users will just be unaware of the fact that we've stopped the container. They will simply run `alidock` that will fire up the container again.

**Comment by mconcas** [comment]
To detect active processes into a container is indeed straightforward ([`Container.top()`](https://docker-py.readthedocs.io/en/stable/containers.html?highlight=top)).
Less trivial is to decide whether the container is actually doing something or not
 - You cannot inspect running processes inside a tmux session, using `ps`
 - If the user uses tmux on regular basis with alidock, you will always find a running tmux session -> you never update 
 - You cannot decide whether a _sleeping_ tmux session is deletable: if I use tmux I probably like to retrieve my last session environment, I really would not like to see everything wiped out only because I dared to not leave a running process inside

**Comment by dberzano** [comment]
@mconcas the container should self-stop. This means that it's something inside the container that should do the job, not `alidock`.

**Comment by mconcas** [comment]
I'd prefer to rely on users' machine reboots than on a timer inside a container, but it's a matter of tastes, I guess... ⏲ 💣

**Comment by dberzano** [comment]
Guys you persuaded me that a time bomb is not the way to go. I am closing this ticket. I think (you might object on that) that an on-screen warning, advising users to "run `alidock stop && alidock` because there may be updates available, is a good compromise that still lets users in charge.
