### ISSUE TITLE
Support python3

### ISSUE THREAD

**Issue by svallero** [alidock/alidock#62]
It would be nice to have the possibility to choose a Python3 environment with proper aliBuild inside the alidock container, for example:
alidock --python3
possibly with a separate path to the build directory so that code built with python2/3 can coexist. 

This would be needed for instance by ML tasks.

**Comment by dberzano** [comment]
alidock is, and will be, a generic tool depending on a certain container underneath: the `--python3` (or so) option would break this statement (note that this has nothing to do with the `--nvidia` option, which uses a different Docker runtime).

We have aliBuild/alienv to manage specific environments (and for the record - we obviously plan to support Python 3 there), alidock is a companion to them, not a replacement. If this is to be done, this is not the right place. Integrating ML with aliBuild means it will work on the Grid too. If we do that with alidock, we'll have to do the work twice.

I hope you understand the issue here 😄

**Comment by svallero** [comment]
Ok, I see the point. Then it would be great to have python3 support in alibuild/alienv.
For the time being I can build a custom image and pass it to alidock with the --image option. Or do you suggest some better strategy?

**Comment by dberzano** [comment]
You can build your own container. This of course implies that you are a bit on your own and you stop benefitting from automatic updates.

You can:

* do that, but base your container upon `alisw/alidock`
* or, much better, you install your ML stuff locally (in `/home/alidock`): you don't need to be root to do that

**Comment by svallero** [comment]
The problem is that I need to build ROOT with python3.

**Comment by dberzano** [comment]
I see, so: is there any chance you can update our alidist recipe for Python in order to use 3.7, and our Python-modules recipe in order to include all the possible ML machinery we need? This would be the one and only solution that fits all use cases 😄

**Comment by dberzano** [comment]
@ginnocen pointed out that we should user Python 3.6 because of some SciKit compatibility problems.
